package guiIO;

import garage.CarInTerm;
import garage.CarOutTerm;

/**
 *
 * @author zsummers
 */
public class TicketGiver extends javax.swing.JFrame {
    private CarInTerm in;
    private CarOutTerm out;
    /**
     * Creates new form TicketGiver
     */
    public TicketGiver(CarInTerm in,CarOutTerm out) {
        initComponents();
        this.in = in;
        this.out = out;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        makeTix = new javax.swing.JButton();
        takeTix = new javax.swing.JButton();
        tixNo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        makeTix.setText("Ticket");
        makeTix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeTixActionPerformed(evt);
            }
        });

        takeTix.setText("Take Ticket");
        takeTix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeTixActionPerformed(evt);
            }
        });

        tixNo.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(makeTix)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tixNo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(takeTix, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(makeTix)
                    .addComponent(tixNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(takeTix)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void takeTixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takeTixActionPerformed
        tixNo.setText("");
    }//GEN-LAST:event_takeTixActionPerformed

    private void makeTixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeTixActionPerformed
        in.newCar();
        tixNo.setText(Integer.toString(in.getLatestId()));
    }//GEN-LAST:event_makeTixActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton makeTix;
    private javax.swing.JButton takeTix;
    private javax.swing.JTextField tixNo;
    // End of variables declaration//GEN-END:variables
}
